// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void KeyboardPopup_Animation(lv_obj_t * TargetObject, int delay);
void KeyboardHide_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_InitialScreen
void ui_InitialScreen_screen_init(void);
lv_obj_t * ui_InitialScreen;
lv_obj_t * ui_SelectGM;
lv_obj_t * ui_SelectSB;
void ui_event_StartButton(lv_event_t * e);
lv_obj_t * ui_StartButton;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Button4;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
lv_obj_t * ui_AverageRad;
lv_obj_t * ui_CumulativeRad;
lv_obj_t * ui_MaximumRad;
lv_obj_t * ui_CumulativeAlarm;
lv_obj_t * ui_CurrentAlarm;
lv_obj_t * ui_Button37;
lv_obj_t * ui_CurrentRad;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Label31;
lv_obj_t * ui_Label32;
lv_obj_t * ui_Label33;
lv_obj_t * ui_Label34;
lv_obj_t * ui_Label35;
lv_obj_t * ui_Label36;
lv_obj_t * ui_Label37;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Label27;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Label38;
// CUSTOM VARIABLES

// SCREEN: ui_Charts1h
void ui_Charts1h_screen_init(void);
lv_obj_t * ui_Charts1h;
lv_obj_t * ui_Container1;
void ui_event_Button8(lv_event_t * e);
lv_obj_t * ui_Button8;
lv_obj_t * ui_Button9;
void ui_event_Button10(lv_event_t * e);
lv_obj_t * ui_Button10;
void ui_event_Button11(lv_event_t * e);
lv_obj_t * ui_Button11;
lv_obj_t * ui_Container6;
void ui_event_Button20(lv_event_t * e);
lv_obj_t * ui_Button20;
lv_obj_t * ui_Label3;
void ui_event_Button21(lv_event_t * e);
lv_obj_t * ui_Button21;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Button22;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Chart1;
// CUSTOM VARIABLES

// SCREEN: ui_VoltageScreen
void ui_VoltageScreen_screen_init(void);
lv_obj_t * ui_VoltageScreen;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Container2;
void ui_event_Button12(lv_event_t * e);
lv_obj_t * ui_Button12;
void ui_event_Button13(lv_event_t * e);
lv_obj_t * ui_Button13;
lv_obj_t * ui_Button14;
void ui_event_Button15(lv_event_t * e);
lv_obj_t * ui_Button15;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Label21;
lv_obj_t * ui_CurrentVoltage;
lv_obj_t * ui_MoreVoltage;
lv_obj_t * ui_Label24;
lv_obj_t * ui_LessVoltage;
lv_obj_t * ui_Label25;
lv_obj_t * ui_TargetVoltage;
lv_obj_t * ui_AutoCalibrate;
lv_obj_t * ui_Label26;
// CUSTOM VARIABLES

// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
lv_obj_t * ui_Settings;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Container4;
void ui_event_Button16(lv_event_t * e);
lv_obj_t * ui_Button16;
void ui_event_Button17(lv_event_t * e);
lv_obj_t * ui_Button17;
void ui_event_Button18(lv_event_t * e);
lv_obj_t * ui_Button18;
lv_obj_t * ui_Button19;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label16;
void ui_event_Keyboard(lv_event_t * e);
lv_obj_t * ui_Keyboard;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_WIFIINFO;
void ui_event_Container10(lv_event_t * e);
lv_obj_t * ui_Container10;
void ui_event_PASSWORD(lv_event_t * e);
lv_obj_t * ui_PASSWORD;
void ui_event_SSID(lv_event_t * e);
lv_obj_t * ui_SSID;
lv_obj_t * ui_Connect;
lv_obj_t * ui_Label18;
lv_obj_t * ui_OnStartup;
lv_obj_t * ui_CurrentSpinbox;
lv_obj_t * ui_CumulativeSpinbox;
lv_obj_t * ui_Container11;
void ui_event_IncCurrent(lv_event_t * e);
lv_obj_t * ui_IncCurrent;
lv_obj_t * ui_Label17;
void ui_event_DecCurrent(lv_event_t * e);
lv_obj_t * ui_DecCurrent;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Container12;
void ui_event_DecCumulative(lv_event_t * e);
lv_obj_t * ui_DecCumulative;
lv_obj_t * ui_Label23;
void ui_event_IncCumulative(lv_event_t * e);
lv_obj_t * ui_IncCumulative;
lv_obj_t * ui_Label28;
lv_obj_t * ui_EnableAlarmsCheckbox;
// CUSTOM VARIABLES

// SCREEN: ui_Charts24h
void ui_Charts24h_screen_init(void);
lv_obj_t * ui_Charts24h;
lv_obj_t * ui_Container5;
void ui_event_Button23(lv_event_t * e);
lv_obj_t * ui_Button23;
lv_obj_t * ui_Button24;
void ui_event_Button25(lv_event_t * e);
lv_obj_t * ui_Button25;
void ui_event_Button26(lv_event_t * e);
lv_obj_t * ui_Button26;
lv_obj_t * ui_Container7;
lv_obj_t * ui_Button27;
lv_obj_t * ui_Label8;
void ui_event_Button28(lv_event_t * e);
lv_obj_t * ui_Button28;
lv_obj_t * ui_Label9;
void ui_event_Button29(lv_event_t * e);
lv_obj_t * ui_Button29;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Chart3;
// CUSTOM VARIABLES

// SCREEN: ui_ChartsSpectrum
void ui_ChartsSpectrum_screen_init(void);
lv_obj_t * ui_ChartsSpectrum;
lv_obj_t * ui_Container8;
void ui_event_Button30(lv_event_t * e);
lv_obj_t * ui_Button30;
lv_obj_t * ui_Button31;
void ui_event_Button32(lv_event_t * e);
lv_obj_t * ui_Button32;
void ui_event_Button33(lv_event_t * e);
lv_obj_t * ui_Button33;
lv_obj_t * ui_Container9;
void ui_event_Button34(lv_event_t * e);
lv_obj_t * ui_Button34;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Button35;
lv_obj_t * ui_Label12;
void ui_event_Button36(lv_event_t * e);
lv_obj_t * ui_Button36;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Chart4;
// CUSTOM VARIABLES

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Startup_screen;
lv_obj_t * ui_Spinner1;
lv_obj_t * ui_Label19;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void KeyboardPopup_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 140, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void KeyboardHide_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 0, 140);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_StartButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_MainScreen_screen_init);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Charts1h, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Charts1h_screen_init);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_VoltageScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_VoltageScreen_screen_init);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_screen_init);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_MainScreen_screen_init);
    }
}

void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_VoltageScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_VoltageScreen_screen_init);
    }
}

void ui_event_Button11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_screen_init);
    }
}

void ui_event_Button20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Charts24h, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Charts24h_screen_init);
    }
}

void ui_event_Button21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ChartsSpectrum, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ChartsSpectrum_screen_init);
    }
}

void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_MainScreen_screen_init);
    }
}

void ui_event_Button13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Charts1h, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Charts1h_screen_init);
    }
}

void ui_event_Button15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_screen_init);
    }
}

void ui_event_Button16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_MainScreen_screen_init);
    }
}

void ui_event_Button17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Charts1h, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Charts1h_screen_init);
    }
}

void ui_event_Button18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_VoltageScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_VoltageScreen_screen_init);
    }
}

void ui_event_Keyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        KeyboardHide_Animation(ui_Keyboard, 0);
    }
}

void ui_event_Container10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        KeyboardPopup_Animation(ui_Keyboard, 0);
    }
}

void ui_event_PASSWORD(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_PASSWORD);
    }
}

void ui_event_SSID(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        KeyboardPopup_Animation(ui_Keyboard, 0);
    }
}

void ui_event_IncCurrent(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_CurrentSpinbox, 1);
    }
}

void ui_event_DecCurrent(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_CurrentSpinbox, -1);
    }
}

void ui_event_DecCumulative(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_CumulativeSpinbox, -1);
    }
}

void ui_event_IncCumulative(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_CumulativeSpinbox, 1);
    }
}

void ui_event_Button23(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_MainScreen_screen_init);
    }
}

void ui_event_Button25(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_VoltageScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_VoltageScreen_screen_init);
    }
}

void ui_event_Button26(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_screen_init);
    }
}

void ui_event_Button28(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ChartsSpectrum, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ChartsSpectrum_screen_init);
    }
}

void ui_event_Button29(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Charts1h, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Charts1h_screen_init);
    }
}

void ui_event_Button30(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_MainScreen_screen_init);
    }
}

void ui_event_Button32(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_VoltageScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_VoltageScreen_screen_init);
    }
}

void ui_event_Button33(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_screen_init);
    }
}

void ui_event_Button34(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Charts24h, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Charts24h_screen_init);
    }
}

void ui_event_Button36(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Charts1h, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Charts1h_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_InitialScreen_screen_init();
    ui_MainScreen_screen_init();
    ui_Charts1h_screen_init();
    ui_VoltageScreen_screen_init();
    ui_Settings_screen_init();
    ui_Charts24h_screen_init();
    ui_ChartsSpectrum_screen_init();
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_InitialScreen);
}
