// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void KeyboardPopup_Animation(lv_obj_t * TargetObject, int delay);
void KeyboardHide_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_InitialScreen
void ui_InitialScreen_screen_init(void);
extern lv_obj_t * ui_InitialScreen;
extern lv_obj_t * ui_SelectGM;
extern lv_obj_t * ui_SelectSB;
void ui_event_StartButton(lv_event_t * e);
extern lv_obj_t * ui_StartButton;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Button4;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_AverageRad;
extern lv_obj_t * ui_CumulativeRad;
extern lv_obj_t * ui_MaximumRad;
extern lv_obj_t * ui_CumulativeAlarm;
extern lv_obj_t * ui_CurrentAlarm;
extern lv_obj_t * ui_Button37;
extern lv_obj_t * ui_CurrentRad;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label38;
// CUSTOM VARIABLES

// SCREEN: ui_Charts1h
void ui_Charts1h_screen_init(void);
extern lv_obj_t * ui_Charts1h;
extern lv_obj_t * ui_Container1;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Button9;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Container6;
void ui_event_Button20(lv_event_t * e);
extern lv_obj_t * ui_Button20;
extern lv_obj_t * ui_Label3;
void ui_event_Button21(lv_event_t * e);
extern lv_obj_t * ui_Button21;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Button22;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Chart1;
// CUSTOM VARIABLES

// SCREEN: ui_VoltageScreen
void ui_VoltageScreen_screen_init(void);
extern lv_obj_t * ui_VoltageScreen;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Container2;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Button14;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_MoreVoltage;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_LessVoltage;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_AutoCalibrate;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_CurrentVoltage;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_TargetVoltage;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_Chart2;
// CUSTOM VARIABLES

// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Container4;
void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Button19;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
void ui_event_Keyboard(lv_event_t * e);
extern lv_obj_t * ui_Keyboard;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_WIFIINFO;
void ui_event_Container10(lv_event_t * e);
extern lv_obj_t * ui_Container10;
void ui_event_PASSWORD(lv_event_t * e);
extern lv_obj_t * ui_PASSWORD;
void ui_event_SSID(lv_event_t * e);
extern lv_obj_t * ui_SSID;
extern lv_obj_t * ui_Connect;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_OnStartup;
extern lv_obj_t * ui_CurrentSpinbox;
extern lv_obj_t * ui_CumulativeSpinbox;
extern lv_obj_t * ui_Container11;
void ui_event_IncCurrent(lv_event_t * e);
extern lv_obj_t * ui_IncCurrent;
extern lv_obj_t * ui_Label17;
void ui_event_DecCurrent(lv_event_t * e);
extern lv_obj_t * ui_DecCurrent;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Container12;
void ui_event_DecCumulative(lv_event_t * e);
extern lv_obj_t * ui_DecCumulative;
extern lv_obj_t * ui_Label23;
void ui_event_IncCumulative(lv_event_t * e);
extern lv_obj_t * ui_IncCumulative;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_EnableAlarmsCheckbox;
// CUSTOM VARIABLES

// SCREEN: ui_Charts24h
void ui_Charts24h_screen_init(void);
extern lv_obj_t * ui_Charts24h;
extern lv_obj_t * ui_Container5;
void ui_event_Button23(lv_event_t * e);
extern lv_obj_t * ui_Button23;
extern lv_obj_t * ui_Button24;
void ui_event_Button25(lv_event_t * e);
extern lv_obj_t * ui_Button25;
void ui_event_Button26(lv_event_t * e);
extern lv_obj_t * ui_Button26;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Button27;
extern lv_obj_t * ui_Label8;
void ui_event_Button28(lv_event_t * e);
extern lv_obj_t * ui_Button28;
extern lv_obj_t * ui_Label9;
void ui_event_Button29(lv_event_t * e);
extern lv_obj_t * ui_Button29;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Chart3;
// CUSTOM VARIABLES

// SCREEN: ui_ChartsSpectrum
void ui_ChartsSpectrum_screen_init(void);
extern lv_obj_t * ui_ChartsSpectrum;
extern lv_obj_t * ui_Container8;
void ui_event_Button30(lv_event_t * e);
extern lv_obj_t * ui_Button30;
extern lv_obj_t * ui_Button31;
void ui_event_Button32(lv_event_t * e);
extern lv_obj_t * ui_Button32;
void ui_event_Button33(lv_event_t * e);
extern lv_obj_t * ui_Button33;
extern lv_obj_t * ui_Container9;
void ui_event_Button34(lv_event_t * e);
extern lv_obj_t * ui_Button34;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Button35;
extern lv_obj_t * ui_Label12;
void ui_event_Button36(lv_event_t * e);
extern lv_obj_t * ui_Button36;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Chart4;
// CUSTOM VARIABLES

// SCREEN: ui_Startup_screen
void ui_Startup_screen_screen_init(void);
extern lv_obj_t * ui_Startup_screen;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label39;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_176188083);    // assets/GMtube (100 x 100 px) (4).png
LV_IMG_DECLARE(ui_img_star_png);    // assets/star.png
LV_IMG_DECLARE(ui_img_radiation_png);    // assets/radiation.png
LV_IMG_DECLARE(ui_img_1345346577);    // assets/bar-chart.png
LV_IMG_DECLARE(ui_img_electricity_png);    // assets/electricity.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_584212719);    // assets/reiniciar (1).png
LV_IMG_DECLARE(ui_img_radscan200x200_png);    // assets/RadScan200x200.png

// FONTS
LV_FONT_DECLARE(ui_font_Pixel);
LV_FONT_DECLARE(ui_font_Pixel_20);
LV_FONT_DECLARE(ui_font_Pixel_60);
LV_FONT_DECLARE(ui_font_SonicSaber);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
