// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_InitialScreen_screen_init(void)
{
    ui_InitialScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_InitialScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_InitialScreen, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InitialScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SelectGM = lv_btn_create(ui_InitialScreen);
    lv_obj_set_width(ui_SelectGM, 100);
    lv_obj_set_height(ui_SelectGM, 100);
    lv_obj_set_x(ui_SelectGM, 80);
    lv_obj_set_y(ui_SelectGM, -10);
    lv_obj_set_align(ui_SelectGM, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_SelectGM, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SelectGM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SelectGM, lv_color_hex(0xA782B7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SelectGM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SelectGM, &ui_img_176188083, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SelectGM, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SelectGM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SelectGM, lv_color_hex(0x1AFF63), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_SelectGM, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_SelectGM, 3, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_SelectGM, lv_color_hex(0x1AFF63), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_SelectGM, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_SelectGM, 30, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_SelectGM, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_SelectSB = lv_btn_create(ui_InitialScreen);
    lv_obj_set_width(ui_SelectSB, 100);
    lv_obj_set_height(ui_SelectSB, 100);
    lv_obj_set_x(ui_SelectSB, -80);
    lv_obj_set_y(ui_SelectSB, -10);
    lv_obj_set_align(ui_SelectSB, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_SelectSB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SelectSB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SelectSB, lv_color_hex(0xA782B7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SelectSB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SelectSB, &ui_img_star_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SelectSB, lv_color_hex(0x1AFF63), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_SelectSB, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_SelectSB, 3, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_color(ui_SelectSB, lv_color_hex(0x1AFF63), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_SelectSB, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_SelectSB, 30, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_SelectSB, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_StartButton = lv_btn_create(ui_InitialScreen);
    lv_obj_set_width(ui_StartButton, 200);
    lv_obj_set_height(ui_StartButton, 50);
    lv_obj_set_x(ui_StartButton, -1);
    lv_obj_set_y(ui_StartButton, -20);
    lv_obj_set_align(ui_StartButton, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_StartButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_StartButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StartButton, lv_color_hex(0x86FD6C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StartButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_StartButton);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, 2);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "START");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_SonicSaber, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_InitialScreen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 2);
    lv_obj_set_y(ui_Label2, -110);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Select the detector installed on the device");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_InitialScreen);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -110);
    lv_obj_set_y(ui_Label5, 58);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "GM Tube");

    ui_Label6 = lv_label_create(ui_InitialScreen);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 110);
    lv_obj_set_y(ui_Label6, 58);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Scintillator");

    lv_obj_add_event_cb(ui_StartButton, ui_event_StartButton, LV_EVENT_ALL, NULL);

}
