// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_Panel4, 480);
    lv_obj_set_height(ui_Panel4, 320);
    lv_obj_set_x(ui_Panel4, -480);
    lv_obj_set_y(ui_Panel4, 0);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_Settings);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 480);
    lv_obj_set_height(ui_Container4, 50);
    lv_obj_set_align(ui_Container4, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button16 = lv_btn_create(ui_Container4);
    lv_obj_set_width(ui_Button16, 120);
    lv_obj_set_height(ui_Button16, 50);
    lv_obj_set_flex_flow(ui_Button16, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button16, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Button16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button16, lv_color_hex(0x5456D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button16, &ui_img_radiation_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button17 = lv_btn_create(ui_Container4);
    lv_obj_set_width(ui_Button17, 120);
    lv_obj_set_height(ui_Button17, 50);
    lv_obj_set_x(ui_Button17, 120);
    lv_obj_set_y(ui_Button17, 0);
    lv_obj_set_align(ui_Button17, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Button17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button17, lv_color_hex(0x7274ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button17, &ui_img_1345346577, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button18 = lv_btn_create(ui_Container4);
    lv_obj_set_width(ui_Button18, 120);
    lv_obj_set_height(ui_Button18, 50);
    lv_obj_set_x(ui_Button18, 240);
    lv_obj_set_y(ui_Button18, 0);
    lv_obj_set_align(ui_Button18, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Button18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button18, lv_color_hex(0x5456D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button18, &ui_img_electricity_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button19 = lv_btn_create(ui_Container4);
    lv_obj_set_width(ui_Button19, 120);
    lv_obj_set_height(ui_Button19, 50);
    lv_obj_set_x(ui_Button19, 360);
    lv_obj_set_y(ui_Button19, 0);
    lv_obj_set_align(ui_Button19, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Button19, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button19, lv_color_hex(0x99D1A2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button19, &ui_img_settings_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_Panel11, 480);
    lv_obj_set_height(ui_Panel11, 2);
    lv_obj_set_x(ui_Panel11, 0);
    lv_obj_set_y(ui_Panel11, 30);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 40);
    lv_obj_set_y(ui_Label14, -87);
    lv_obj_set_align(ui_Label14, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label14, "Wifi Setup");

    ui_Label15 = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 40);
    lv_obj_set_y(ui_Label15, 70);
    lv_obj_set_align(ui_Label15, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label15, "Current Alarm");

    ui_Label16 = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 40);
    lv_obj_set_y(ui_Label16, 120);
    lv_obj_set_align(ui_Label16, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label16, "Cumulative Alarm");

    ui_CumulativeAlarmSlider = lv_slider_create(ui_Settings);
    lv_slider_set_value(ui_CumulativeAlarmSlider, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_CumulativeAlarmSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_CumulativeAlarmSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_CumulativeAlarmSlider, 400);
    lv_obj_set_height(ui_CumulativeAlarmSlider, 10);
    lv_obj_set_x(ui_CumulativeAlarmSlider, 0);
    lv_obj_set_y(ui_CumulativeAlarmSlider, 140);
    lv_obj_set_align(ui_CumulativeAlarmSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_CumulativeAlarmSlider, lv_color_hex(0xFFA1A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CumulativeAlarmSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_CumulativeAlarmSlider, lv_color_hex(0xFF3434), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CumulativeAlarmSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_CumulativeAlarmSlider, lv_color_hex(0xFF4848), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CumulativeAlarmSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_CurrentAlarmSlider = lv_slider_create(ui_Settings);
    lv_slider_set_value(ui_CurrentAlarmSlider, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_CurrentAlarmSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_CurrentAlarmSlider, 0,
                                                                                                       LV_ANIM_OFF);
    lv_obj_set_width(ui_CurrentAlarmSlider, 400);
    lv_obj_set_height(ui_CurrentAlarmSlider, 10);
    lv_obj_set_x(ui_CurrentAlarmSlider, 0);
    lv_obj_set_y(ui_CurrentAlarmSlider, 90);
    lv_obj_set_align(ui_CurrentAlarmSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_CurrentAlarmSlider, lv_color_hex(0xFFA1A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CurrentAlarmSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_CurrentAlarmSlider, lv_color_hex(0xFF3434), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CurrentAlarmSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_CurrentAlarmSlider, lv_color_hex(0xFF4848), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CurrentAlarmSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Keyboard = lv_keyboard_create(ui_Settings);
    lv_obj_set_width(ui_Keyboard, 480);
    lv_obj_set_height(ui_Keyboard, 130);
    lv_obj_set_x(ui_Keyboard, 0);
    lv_obj_set_y(ui_Keyboard, 140);
    lv_obj_set_align(ui_Keyboard, LV_ALIGN_BOTTOM_MID);

    ui_Panel12 = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_Panel12, 247);
    lv_obj_set_height(ui_Panel12, 43);
    lv_obj_set_x(ui_Panel12, 96);
    lv_obj_set_y(ui_Panel12, -49);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x0E0E0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFIINFO = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_WIFIINFO, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WIFIINFO, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WIFIINFO, -6);
    lv_obj_set_y(ui_WIFIINFO, -12);
    lv_label_set_text(ui_WIFIINFO, "Disconnected\n");

    ui_Container10 = lv_obj_create(ui_Settings);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 153);
    lv_obj_set_height(ui_Container10, 90);
    lv_obj_set_x(ui_Container10, -130);
    lv_obj_set_y(ui_Container10, -24);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PASSWORD = lv_textarea_create(ui_Container10);
    lv_obj_set_width(ui_PASSWORD, 150);
    lv_obj_set_height(ui_PASSWORD, 43);
    lv_obj_set_x(ui_PASSWORD, 0);
    lv_obj_set_y(ui_PASSWORD, 20);
    lv_obj_set_align(ui_PASSWORD, LV_ALIGN_LEFT_MID);
    lv_textarea_set_placeholder_text(ui_PASSWORD, "Password");
    lv_textarea_set_password_mode(ui_PASSWORD, true);
    lv_obj_set_style_bg_color(ui_PASSWORD, lv_color_hex(0x959595), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PASSWORD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_SSID = lv_textarea_create(ui_Container10);
    lv_obj_set_width(ui_SSID, 150);
    lv_obj_set_height(ui_SSID, 43);
    lv_obj_set_x(ui_SSID, 0);
    lv_obj_set_y(ui_SSID, -25);
    lv_obj_set_align(ui_SSID, LV_ALIGN_LEFT_MID);
    lv_textarea_set_placeholder_text(ui_SSID, "SSID");
    lv_obj_set_style_bg_color(ui_SSID, lv_color_hex(0x959595), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SSID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Connect = lv_btn_create(ui_Settings);
    lv_obj_set_width(ui_Connect, 80);
    lv_obj_set_height(ui_Connect, 20);
    lv_obj_set_x(ui_Connect, 18);
    lv_obj_set_y(ui_Connect, 0);
    lv_obj_set_align(ui_Connect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Connect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Connect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Connect, lv_color_hex(0x7DFF8F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Connect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Connect);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Connect");

    ui_OnStartup = lv_checkbox_create(ui_Settings);
    lv_checkbox_set_text(ui_OnStartup, "Connect On Startup");
    lv_obj_set_width(ui_OnStartup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnStartup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnStartup, 143);
    lv_obj_set_y(ui_OnStartup, 0);
    lv_obj_set_align(ui_OnStartup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OnStartup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_OnStartup, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button16, ui_event_Button16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button17, ui_event_Button17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button18, ui_event_Button18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard, ui_event_Keyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PASSWORD, ui_event_PASSWORD, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SSID, ui_event_SSID, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container10, ui_event_Container10, LV_EVENT_ALL, NULL);

}
