// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Startup_screen_screen_init(void)
{
    ui_Startup_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Startup_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Startup_screen);
    lv_img_set_src(ui_Image1, &ui_img_radscan200x200_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label19 = lv_label_create(ui_Startup_screen);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 0);
    lv_obj_set_y(ui_Label19, 80);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Loading...");

    ui_Label39 = lv_label_create(ui_Startup_screen);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, 10);
    lv_obj_set_y(ui_Label39, -10);
    lv_obj_set_align(ui_Label39, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label39, "V1.0.1");
    lv_obj_set_style_text_font(ui_Label39, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

}
