// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Button7;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_176188083);    // assets/GMtube (100 x 100 px) (4).png
LV_IMG_DECLARE(ui_img_383071526);    // assets/SurfaceBarrier (2).png
LV_IMG_DECLARE(ui_img_85097194);    // assets/gear (1) (1).png
LV_IMG_DECLARE(ui_img_220545925);    // assets/bar-chart (1).png
LV_IMG_DECLARE(ui_img_1666199263);    // assets/lightning (1).png
LV_IMG_DECLARE(ui_img_290762343);    // assets/switch (1).png

// FONTS
LV_FONT_DECLARE(ui_font_SonicSaber);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
